from typing import Any

class Menu:
    is_animating: str

    def __init__(self, *_args: Any, **_kwargs: Any) -> None: ...
    def update(self, _delta: int) -> None: ...
    def draw(self, _ctx: Any) -> None: ...
    def _cleanup(self) -> None: ...
