from typing import Any

class Menu:
    is_animating: str

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def update(self, delta: int) -> None: ...
    def draw(self, ctx: Any) -> None: ...
