from typing import Any

class Notification:
    def __init__(self, _text: str, **_kwargs: Any) -> None: ...
    def update(self, _delta: int) -> None: ...
    def draw(self, _ctx: Any) -> None: ...
    def _is_closed(self) -> bool: ...
