from typing import Any, Callable

FLAG_READ: int
FLAG_WRITE: int
FLAG_NOTIFY: int
FLAG_INDICATE: int
FLAG_WRITE_NO_RESPONSE: int


class UUID:
    def __init__(self, _value: int | str | bytes | bytearray) -> None: ...
    def __bytes__(self) -> bytes: ...


class BLE:
    def __init__(self, *_args: Any, **_kwargs: Any) -> None: ...
    def active(self, _state: bool | None = None) -> bool: ...
    def irq(self, _handler: Callable[[int, Any], None] | None) -> None: ...

    def gatts_register_services(self, _services: Any) -> Any: ...
    def gatts_read(self, _value_handle: int) -> bytes: ...
    def gatts_write(self, _value_handle: int, _data: bytes | bytearray | str) -> None: ...
    def gatts_notify(self, _conn_handle: int, _value_handle: int, _data: bytes | bytearray | str = b"") -> None: ...

    def gap_advertise(self, _interval_us: int | None = None, **_kwargs: Any) -> None: ...
