from typing import Any

class Pin:
    IN: int
    OUT: int

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def init(self, *args: Any, **kwargs: Any) -> None: ...
    def value(self, *args: Any) -> int: ...

class PWM:
    def __init__(self, pin: Pin, *args: Any, **kwargs: Any) -> None: ...
    def freq(self, *args: Any) -> int: ...
    def duty_u16(self, *args: Any) -> int: ...
    def duty_ns(self, *args: Any) -> int: ...
    def deinit(self) -> None: ...

class I2C:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def readfrom_mem(self, addr: int, memaddr: int, nbytes: int, *args: Any, **kwargs: Any) -> bytes: ...

def disable_irq() -> int: ...
def enable_irq(state: int) -> None: ...
