from typing import Any

class Pin:
    IN: int
    OUT: int

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def init(self, *args: Any, **kwargs: Any) -> None: ...
    def value(self, *args: Any) -> int: ...

class PWM:
    def __init__(self, pin: Pin, *args: Any, **kwargs: Any) -> None: ...
    def freq(self, *args: Any) -> int: ...
    def duty_u16(self, *args: Any) -> int: ...
    def duty_ns(self, *args: Any) -> int: ...
    def deinit(self) -> None: ...

class I2C:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def readfrom_mem(self, addr: int, memaddr: int, nbytes: int, *args: Any, **kwargs: Any) -> bytes: ...
    def writeto_mem(self, addr: int, memaddr: int, buf: bytes, *args: Any, **kwargs: Any) -> None: ...
    def writeto(self, addr: int, buf: bytes, stop: bool = True) -> int: ...
    def readfrom(self, addr: int, nbytes: int, stop: bool = True) -> bytes: ...

class Timer:
    PERIODIC: int
    ONE_SHOT: int

    def __init__(self, id: int = -1, *args: Any, **kwargs: Any) -> None: ...
    def init(self, *args: Any, **kwargs: Any) -> None: ...
    def deinit(self) -> None: ...

class _Mem32:
    def __getitem__(self, addr: int) -> int: ...
    def __setitem__(self, addr: int, value: int) -> None: ...

mem32: _Mem32

def disable_irq() -> int: ...
def enable_irq(state: int) -> None: ...
