from typing import Any, Union, Callable, TypeVar

_T = TypeVar("_T", int, float, str, bytes, bool)

def const(x: _T) -> _T: ...
def mem_info(verbose: bool = False) -> None: ...
def qstr_info(verbose: bool = False) -> None: ...
def stack_use() -> int: ...
def heap_lock() -> None: ...
def heap_unlock() -> None: ...
def kbd_intr(chr: int) -> None: ...
def schedule(func: object, arg: object) -> None: ...

_F = TypeVar("_F", bound=Callable[..., Any])

def native(f: _F) -> _F: ...
def viper(f: _F) -> _F: ...

# Structural proxy type for 32-bit memory window array pointers
class _ViperPtr32:
    def __getitem__(self, index: int) -> int: ...
    def __setitem__(self, index: int, value: int) -> None: ...

# Allow ptr32 to accept memoryview, array, bytearray, or a raw memory address
def ptr32(obj: Union[int, Any]) -> _ViperPtr32: ...
