from typing import Any

class HexpansionHeader:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

def write_header(i2c: Any, addr: int, header: HexpansionHeader, *args: Any, **kwargs: Any) -> None: ...
def read_header(i2c: Any, addr: int, *args: Any, **kwargs: Any) -> HexpansionHeader: ...
