from typing import Any

def get_hexpansion_block_devices(_i2c: Any, _header: Any, _addr: int, *_args: Any, **_kwargs: Any) -> tuple[Any, Any]: ...
def detect_eeprom_addr(_i2c: Any, *_args: Any, **_kwargs: Any) -> tuple[int | None, int | None]: ...
def get_app_by_slot(_slot: int) -> Any: ...
def get_slots_by_vid_pid(_vid: int, _pid: int) -> list[int]: ...