from typing import Any

class _EventBus:
    def on(self, _event_type: Any, _handler: Any, _owner: Any) -> None: ...
    def on_async(self, _event_type: Any, _handler: Any, _owner: Any) -> None: ...
    def remove(self, _event_type: Any, _handler: Any, _owner: Any) -> None: ...
    def emit(self, _event: Any) -> None: ...

eventbus: _EventBus
