from typing import Any

class _EventBus:
    def on_async(self, event_type: Any, handler: Any, owner: Any) -> None: ...
    def remove(self, event_type: Any, handler: Any, owner: Any) -> None: ...
    def emit(self, event: Any) -> None: ...

eventbus: _EventBus
